import Register
def shifter(inst):
    R=["0000"+inst[6:10],"0000"+inst[10:14]]
    if(inst[1]=="0"):
        R.append("0000"+inst[14:])
    R_val=[]
    i=1
    while(i<len(R)):
        R_val.append(Register.get_from_reg(R[i]))
        i+=1
    if(inst[1:3]=="00"):
        if(R_val[1][0]=="1"):
            shift=Register.compliment(R_val[1])
            R_val[0]=format(int(R_val[0],2)//(2**shift),"016b")
        else:
            shift=int(R_val[1][1:],2)
            R_val[0]=format(int(R_val[0],2)*(2**(shift+1)),"016b")
            R_val[0]=R_val[0][-17:-1]
            Register.put_to_reg(R[0],R_val[0])
    elif(inst[1:3]=="01"):
        if(R_val[1][0]=="1"):
            print("!!")
            print(R_val[1])
            shift=Register.compliment(R_val[1])%16
            print(shift)
            Register.put_to_reg(R[0],R_val[0][16-shift:]+R_val[0][0:16-shift])
            print(Register.get_from_reg(R[1]))
            print(Register.get_from_reg(R[0]))
        else:
            print("!!!")
            shift=int(R_val[1][1:],2)%16
            print(shift)
            Register.put_to_reg(R[0],R_val[0][shift:]+R_val[0][0:shift])
            print(Register.get_from_reg(R[1]))
            print(Register.get_from_reg(R[0]))
    elif(inst[1:3]=="10"):
        Register.put_to_reg(R[0],Register.int_to_hex(len(R_val[0].split("1")[0])))
        print(Register.get_from_reg(R[0]))
    elif(inst[1:3]=="11"):
        Register.put_to_reg(R[0],Register.int_to_hex(len(R_val[0].split("0")[0])))
        print(Register.get_from_reg(R[0]))
x=input()
while(x!="#"):
    shifter(x)
    x=input()